# Generated by Django 4.1 on 2022-09-26 11:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('category', models.CharField(max_length=20)),
                ('notice', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
