# Generated by Django 3.2 on 2022-09-29 09:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_vision', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
