# Generated by Django 3.2 on 2022-09-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ourvision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourvision',
            name='our_vision',
            field=models.TextField(),
        ),
    ]
