# Generated by Django 3.2 on 2022-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ourvision_our_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('students', models.SmallIntegerField()),
                ('faculty', models.SmallIntegerField()),
            ],
        ),
    ]
