# Generated by Django 3.2 on 2022-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='content',
            field=models.CharField(max_length=350),
        ),
    ]
