# Generated by Django 3.2 on 2022-09-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_header_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='content',
            field=models.CharField(max_length=600),
        ),
    ]
