# Generated by Django 3.2 on 2022-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormerPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=220)),
                ('name', models.ImageField(upload_to='')),
            ],
        ),
    ]
