# Generated by Django 3.2 on 2022-09-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_formerprincipal_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formerprincipal',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='formerprincipal',
            name='name',
            field=models.CharField(max_length=220),
        ),
    ]
