# Generated by Django 3.2 on 2022-09-30 10:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220929_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=220)),
                ('about', ckeditor.fields.RichTextField()),
                ('link', models.URLField(max_length=800)),
            ],
        ),
    ]
