# Generated by Django 4.1 on 2022-12-02 16:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_notice_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
