# Generated by Django 3.2 on 2022-12-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20221209_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogoImage',
        ),
    ]
