# Generated by Django 3.2 on 2022-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesection', '0002_alter_onlinesection_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinesection',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
