# Generated by Django 3.2 on 2022-12-11 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesection', '0003_alter_onlinesection_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinesection',
            name='created_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
