# Generated by Django 3.2 on 2022-12-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesection', '0004_onlinesection_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinesection',
            name='created_date',
        ),
    ]
