# Generated by Django 3.2 on 2022-12-05 16:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=220)),
                ('position', models.CharField(max_length=220)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('location', models.CharField(blank=True, max_length=220, null=True)),
                ('about', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
