# Generated by Django 3.2 on 2022-12-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='honors_awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
