# Generated by Django 3.2 on 2022-12-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_staffheader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='position',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='staff',
            name='number_position',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
