# Generated by Django 3.2 on 2022-12-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_alter_staff_number_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='number_position',
            new_name='number_in_order',
        ),
    ]
