# Generated by Django 3.2 on 2022-12-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
