# Generated by Django 3.2 on 2022-12-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_head_of_department_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
