# Generated by Django 4.1 on 2022-12-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_departmentheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
